### ISSUE TITLE
with_skipper impossible to use in practice

### ISSUE THREAD

**Issue by DFINITYManu** [ttys3/axum-otel-metrics#75]
In practice, anything that can be dynamic cannot be used in `with_skipper` on the HttpMetricsBuilderLayer, because the function that is supposed to be doing the skipping cannot be defined as an `fn` since it captures local state, and it cannot be defined as a closure either since the closure cannot be coerced to an `fn` since it captures local state.

![image](https://github.com/ttys3/axum-otel-metrics/assets/123385598/57de4d33-e874-4a6a-9d9b-e6eb16d2199d)

![image](https://github.com/ttys3/axum-otel-metrics/assets/123385598/ec24f76a-8a49-4fc0-b27c-0920e4d34688)

How do we change the API so this works?  Alternatively, is there something that I can do, as the caller of the code, to make this work?

**Comment by ttys3** [comment]
PR is welcome

**Comment by DFINITYManu** [comment]
I would have made PR if I knew how to fix this.  I was more asking for advice.  If you know how to do this, I will gladly make the PR in the next few minutes.

**Comment by DFINITYManu** [comment]
I believe I will open a PR soon to fix this.
